import js from "@eslint/js";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "@typescript-eslint/eslint-plugin";
import tsparser from "@typescript-eslint/parser";

export default [
  {
    ignores: ["dist/**", "node_modules/**"],
  },
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsparser,
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        fetch: "readonly",
        console: "readonly",
        navigator: "readonly",
        alert: "readonly",
        confirm: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        process: "readonly",
        Map: "readonly",
        Set: "readonly",
        JSON: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        MessageEvent: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLAnchorElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLLabelElement: "readonly",
        HTMLTableElement: "readonly",
        HTMLTableRowElement: "readonly",
        HTMLTableCellElement: "readonly",
        HTMLTableSectionElement: "readonly",
        HTMLTableColElement: "readonly",
        HTMLTableCaptionElement: "readonly",
        HTMLOListElement: "readonly",
        HTMLUListElement: "readonly",
        HTMLLIElement: "readonly",
        HTMLDListElement: "readonly",
        HTMLDataListElement: "readonly",
        HTMLFieldSetElement: "readonly",
        HTMLLegendElement: "readonly",
        HTMLDetailsElement: "readonly",
        HTMLSummaryElement: "readonly",
        HTMLDialogElement: "readonly",
        HTMLSlotElement: "readonly",
        HTMLTemplateElement: "readonly",
        HTMLPictureElement: "readonly",
        HTMLSourceElement: "readonly",
        HTMLMediaElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLAudioElement: "readonly",
        HTMLTrackElement: "readonly",
        HTMLScriptElement: "readonly",
        HTMLStyleElement: "readonly",
        HTMLMetaElement: "readonly",
        HTMLLinkElement: "readonly",
        HTMLTitleElement: "readonly",
        HTMLHeadElement: "readonly",
        HTMLBodyElement: "readonly",
        HTMLHtmlElement: "readonly",
        HTMLFrameElement: "readonly",
        HTMLIFrameElement: "readonly",
        HTMLObjectElement: "readonly",
        HTMLEmbedElement: "readonly",
        HTMLParamElement: "readonly",
        HTMLAreaElement: "readonly",
        HTMLMapElement: "readonly",
        FormData: "readonly",
      },
    },
    plugins: {
      react,
      "react-hooks": reactHooks,
      "@typescript-eslint": tseslint,
    },
    rules: {
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { 
        "argsIgnorePattern": "^_",
        "varsIgnorePattern": "^_",
        "caughtErrorsIgnorePattern": "^_"
      }],
      "@typescript-eslint/no-explicit-any": "off",
    },
    settings: {
      react: {
        version: "detect",
      },
    },
  },
];
