import {issueTradeStatement} from './tradeStatementIssue';
import {afterAll,beforeAll,describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import * as admin from 'firebase-admin';
import {deleteIssuedStatement,statementOriginalHash} from './deleteIssuedStatementCommand';
import {issueVoucher,voucherSequenceKey} from './voucherIssue';
const available=process.env.FIRESTORE_EMULATOR_HOST==='127.0.0.1:8082';
const run='delete-'+randomUUID(),company='taebaek',partner=run+'-partner';
let app:admin.app.App,db:admin.firestore.Firestore;const owned=new Set<string>();
const ref=(group:string,id:string)=>{owned.add(group+'/'+id);return db.collection(group).doc(id);};
const state=()=>ref('appMeta',`partnerPaymentState_${company}_${partner}`);
async function seed(suffix:string){const id=run+'-'+suffix;await Promise.all([ref('appMeta','releaseCutover').set({status:'active',releaseId:run,voucherNotBefore:{taebaek:'2026-10-03'},testRunId:run}),ref('issuedStatements',id).set({companyId:company,partnerId:partner,orderId:id+'-order',sourcePoId:id+'-po',tradeDate:'2026-10-08',totalSupply:100,totalTax:10,totalAmount:110,docNo:'261008-001'}),ref('orders',id+'-order').set({companyId:company,linkedStatementId:id,linkedStatementAt:'old',status:'DONE',stock:7,lots:[{qty:7}]}),ref('purchaseOrders',id+'-po').set({companyId:company,linkedStatementId:id,linkedStatementAt:'old',status:'invoiced',invoicedAt:'old',items:[{quantity:7}]}),ref('settlements',id+'-settlement').set({companyId:company,statementId:id,cashEntryId:id+'-cash',amount:110}),state().set({companyId:company,partnerId:partner,revision:3,extra:'보존'}),ref('cashEntries',id+'-cash').set({companyId:company,amount:110,docNo:'출금번호'})]);return id;}
async function command(id:string){return {operationId:id+'-delete',statementId:id,releaseId:run,expectedRevision:0,expectedOriginalHash:statementOriginalHash((await ref('issuedStatements',id).get()).data()!)};}
describe.skipIf(!available)('서버 전표 삭제의 원자성과 원 발행 재시도',{timeout:60000},()=>{
 beforeAll(()=>{app=admin.initializeApp({projectId:'demo-taebaekfood-local'},run);db=admin.firestore(app);});
 afterAll(async()=>{if(!db)return;for(const path of owned){const r=db.doc(path);if(path==='appMeta/releaseCutover'&&(await r.get()).get('testRunId')!==run)continue;await r.delete();}await app.delete();});
 it('동시 삭제와 재시도는 연결·정산만 한 번 없애고 재고·상태·현금을 보존한다',async()=>{const id=await seed('atomic'),input=await command(id);ref('voucherMutationOperations',input.operationId);const cash=await ref('cashEntries',id+'-cash').get();const results=await Promise.all([deleteIssuedStatement(db,company,'actor',input),deleteIssuedStatement(db,company,'actor',input)]);expect(results.map(x=>x.status).sort()).toEqual(['applied','duplicate']);expect((await ref('issuedStatements',id).get()).exists).toBe(false);expect((await ref('settlements',id+'-settlement').get()).exists).toBe(false);expect((await ref('orders',id+'-order').get()).data()).toEqual({companyId:company,status:'DONE',stock:7,lots:[{qty:7}]});expect((await ref('purchaseOrders',id+'-po').get()).data()).toEqual({companyId:company,status:'invoiced',invoicedAt:'old',items:[{quantity:7}]});expect((await state().get()).data()).toMatchObject({revision:4,extra:'보존'});expect((await ref('cashEntries',id+'-cash').get()).updateTime!.isEqual(cash.updateTime!)).toBe(true);expect((await deleteIssuedStatement(db,company,'actor',input)).status).toBe('duplicate');});
 it('원문 변경과 다른 회사는 금융·연결·감사를 쓰지 않는다',async()=>{for(const mode of ['changed','foreign']){const id=await seed(mode),input=await command(id);if(mode==='changed')await ref('issuedStatements',id).update({totalAmount:220});else await ref('orders',id+'-order').update({companyId:'punghoe'});const before=await ref('issuedStatements',id).get();await expect(deleteIssuedStatement(db,company,'actor',input)).rejects.toThrow();expect((await ref('issuedStatements',id).get()).updateTime!.isEqual(before.updateTime!)).toBe(true);expect((await ref('settlements',id+'-settlement').get()).exists).toBe(true);expect((await ref('voucherMutationOperations',input.operationId).get()).get('status')).toBe('rejected');await expect(deleteIssuedStatement(db,company,'actor',input)).rejects.toMatchObject({details:{operationStatus:'rejected',operationId:input.operationId,statementId:id,companyId:company}});}});
 it('일반 발행 삭제 뒤 원 요청 재시도는 원 번호만 반환하고 전표·카운터를 재생성하지 않는다',async()=>{const id=run+'-numbered';await ref('appMeta','releaseCutover').set({status:'active',releaseId:run,voucherNotBefore:{taebaek:'2026-10-03'},testRunId:run});const counter=ref('appMeta',voucherSequenceKey(company,'2026-10-08'));await counter.set({companyId:company,tradeDate:'2026-10-08',prefix:'',last:10});ref('issuedStatements',id);const input={kind:'issuedStatements' as const,operationId:id,tradeDate:'2026-10-08',releaseId:run,document:{tradeDate:'2026-10-08',totalSupply:100,totalTax:10,totalAmount:110}};const issued=await issueVoucher(db,company,input),stale=await command(id);stale.operationId=id+'-stale';ref('voucherMutationOperations',stale.operationId);await ref('issuedStatements',id).update({mutationRevision:1});await expect(deleteIssuedStatement(db,company,'actor',stale)).rejects.toMatchObject({details:{operationStatus:'rejected'}});const del={...await command(id),expectedRevision:1};ref('voucherMutationOperations',del.operationId);await deleteIssuedStatement(db,company,'actor',del);const before=await counter.get();expect(await issueVoucher(db,company,input)).toEqual(issued);expect((await ref('issuedStatements',id).get()).exists).toBe(false);expect((await counter.get()).updateTime!.isEqual(before.updateTime!)).toBe(true);await ref('voucherMutationOperations',del.operationId).update({beforeHash:'0'.repeat(64)});await expect(issueVoucher(db,company,input)).rejects.toThrow('감사');});

 it('거래 전표 원 발행 재시도는 삭제된 주문 연결을 복구하지 않는다',async()=>{const id=run+'-trade',order=id+'-order';await Promise.all([ref('appMeta','releaseCutover').set({status:'active',releaseId:run,voucherNotBefore:{taebaek:'2026-10-03'},testRunId:run}),ref('partners',partner).set({companyId:company,name:'거래처'}),ref('accountCodes',run+'-code').set({companyId:company,code:'800'}),ref('orders',order).set({companyId:company,partnerId:partner,status:'DONE'}),ref('appMeta',voucherSequenceKey(company,'2026-10-08')).set({companyId:company,tradeDate:'2026-10-08',prefix:'',last:20})]);ref('issuedStatements',id);const input={operationId:id+':ISSUE',releaseId:run,orderIds:[order],poIds:[],costUpdates:[],statement:{id,companyId:company,type:'매출',partnerId:partner,partnerName:'거래처',orderId:order,tradeDate:'2026-10-08',totalSupply:100,totalTax:0,totalAmount:100,items:[{itemId:run+'-item',name:'상품',qty:1,price:100,supply:100,tax:0,total:100,isTaxExempt:true,accountCode:'800'}]}};const issued=await issueTradeStatement(db,company,'actor',input),del=await command(id);ref('voucherMutationOperations',del.operationId);await deleteIssuedStatement(db,company,'actor',del);const before=await ref('appMeta',voucherSequenceKey(company,'2026-10-08')).get();expect(await issueTradeStatement(db,company,'actor',input)).toEqual({...issued,status:'duplicate'});expect((await ref('orders',order).get()).data()).toEqual({companyId:company,partnerId:partner,status:'DONE'});expect((await ref('issuedStatements',id).get()).exists).toBe(false);expect((await before.ref.get()).updateTime!.isEqual(before.updateTime!)).toBe(true);});
 it('같은 전표·revision을 읽는 동시 정산은 삭제 뒤 고아 문서를 남기지 않는다',async()=>{const id=await seed('race'),input=await command(id),settlement=ref('settlements',id+'-new');ref('voucherMutationOperations',input.operationId);const create=async()=>db.runTransaction(async tx=>{const [s,p]=await Promise.all([tx.get(ref('issuedStatements',id)),tx.get(state())]);if(!s.exists)throw new Error('전표 없음');tx.create(settlement,{companyId:company,statementId:id,amount:5});tx.update(state(),{revision:p.get('revision')+1});});const results=await Promise.allSettled([create(),deleteIssuedStatement(db,company,'actor',input)]);expect(results[1].status).toBe('fulfilled');expect((await settlement.get()).exists).toBe(false);expect((await db.collection('settlements').where('companyId','==',company).where('statementId','==',id).get()).empty).toBe(true);await expect(create()).rejects.toThrow('전표 없음');}); it('revision 사전 거절은 감사 한 건만 확정하고 원문·정산은 보존한다',async()=>{const id=await seed('terminal'),input=await command(id);ref('voucherMutationOperations',input.operationId);await ref('issuedStatements',id).update({mutationRevision:1});const before=await Promise.all([ref('issuedStatements',id).get(),ref('settlements',id+'-settlement').get(),state().get()]);await expect(deleteIssuedStatement(db,company,'actor',input)).rejects.toMatchObject({details:{operationStatus:'rejected'}});const receipt=await ref('voucherMutationOperations',input.operationId).get();expect(receipt.data()).toMatchObject({status:'rejected',command:input,createdBy:'actor'});await ref('appMeta','releaseCutover').update({status:'paused'});await expect(deleteIssuedStatement(db,company,'actor',input)).rejects.toMatchObject({details:{operationStatus:'rejected'}});expect((await receipt.ref.get()).updateTime!.isEqual(receipt.updateTime!)).toBe(true);for(const original of before)expect((await original.ref.get()).updateTime!.isEqual(original.updateTime!)).toBe(true);});
});

