import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { randomUUID } from 'node:crypto';
import * as admin from 'firebase-admin';
vi.mock('firebase-functions/v2/https',()=>({HttpsError:class extends Error{constructor(public code:string,message:string,public details?:unknown){super(message);}},onCall:(_o:unknown,h:unknown)=>h}));
import { recordPartnerPayment } from './partnerPaymentCommand';
const available=process.env.FIRESTORE_EMULATOR_HOST==='127.0.0.1:8082';
const runId=`payment-${randomUUID()}`,date='2026-10-03',releaseId=runId;
const bankId=`${runId}-bank`,partnerId=`${runId}-partner`,statementId=`${runId}-statement`,counterId=`voucherNo_taebaek_${date}_general`,stateId=`partnerPaymentState_taebaek_${partnerId}`;
let app:admin.app.App,db:admin.firestore.Firestore;
const owned=new Set<string>();const ref=(c:string,id:string)=>db.collection(c).doc(id);
async function put(c:string,id:string,value:Record<string,unknown>){await ref(c,id).set({...value,testRunId:runId});owned.add(`${c}/${id}`);}
async function clear(){for(const c of ['cashEntries','partnerPaymentOperations','settlements'])for(const s of (await db.collection(c).get()).docs){if((s.id.startsWith(runId)||s.get('operationId')?.startsWith(runId))&&s.get('companyId')==='taebaek'){owned.add(s.ref.path);await s.ref.delete();}}
 const state=await ref('appMeta',stateId).get();if(state.exists){owned.add(state.ref.path);await state.ref.delete();}}
async function seed(){await clear();await Promise.all([
 put('appMeta','releaseCutover',{releaseId,status:'active',voucherNotBefore:{taebaek:date}}),put('appMeta','partnerPaymentCutover_taebaek',{companyId:'taebaek',enabled:true,legacyWritersBlocked:true,auditPassed:true}),
 put('appMeta',counterId,{companyId:'taebaek',tradeDate:date,prefix:'',last:0}),put('partners',partnerId,{companyId:'taebaek',name:'검증 거래처'}),put('cashAccounts',bankId,{companyId:'taebaek',type:'통장',active:true}),
 put('issuedStatements',statementId,{companyId:'taebaek',partnerId,type:'매출',tradeDate:date,totalAmount:100,totalSupply:100,totalTax:0,items:[{accountCode:'800',supply:100,tax:0,total:100}]})]);}
const input=(label:string)=>({operationId:`${runId}-${label}`,tradeDate:date,partnerId,direction:'입금' as const,amount:100,cashAccountId:bankId,pin:true,allocations:[{statementId,amount:100}],expectedRevision:0,releaseId});
const issue=(r:ReturnType<typeof input>,store=db)=>recordPartnerPayment(store,'taebaek',`${runId}-admin`,r);
async function financialZero(r:ReturnType<typeof input>,revision:number|null=null){expect((await ref('cashEntries',r.operationId).get()).exists).toBe(false);expect((await ref('issuedStatements',r.operationId).get()).exists).toBe(false);expect((await db.collection('settlements').where('operationId','==',r.operationId).get()).size).toBe(0);expect((await ref('appMeta',counterId).get()).get('last')).toBe(0);const state=await ref('appMeta',stateId).get();expect(state.exists?state.get('revision'):null).toBe(revision);expect((await ref('issuedStatements',statementId).get()).get('totalAmount')).toBe(100);}
const rejection=(r:ReturnType<typeof input>)=>({details:{partnerPaymentFailure:{version:1,companyId:'taebaek',partnerId,operationId:r.operationId,operationRejected:true,financialWrites:false}}});
describe.skipIf(!available)('partner payment durable failure actual Admin SDK',()=>{
 beforeAll(async()=>{app=admin.initializeApp({projectId:'demo-taebaekfood-local'},runId);db=admin.firestore(app);});
 afterAll(async()=>{if(!db)return;await clear();for(const path of owned){const target=db.doc(path),s=await target.get();if(s.exists&&s.get('testRunId')===runId)await target.delete();}for(const path of owned)expect((await db.doc(path).get()).exists).toBe(false);for(const c of ['cashEntries','partnerPaymentOperations','settlements'])expect((await db.collection(c).get()).docs.filter(s=>s.id.startsWith(runId)||s.get('operationId')?.startsWith(runId))).toHaveLength(0);await app.delete();});
 it('gate 부재 거절은 감사만 확정하며 정책 복구 후에도 같은 작업은 거절',async()=>{await seed();await ref('appMeta','partnerPaymentCutover_taebaek').delete();const r=input('gate');await expect(issue(r)).rejects.toMatchObject(rejection(r));const op=await ref('partnerPaymentOperations',r.operationId).get();expect(op.get('status')).toBe('rejected');expect(op.get('requestHash')).toMatch(/^[a-f0-9]{64}$/);await financialZero(r);await put('appMeta','partnerPaymentCutover_taebaek',{companyId:'taebaek',enabled:true,legacyWritersBlocked:true,auditPassed:true});await expect(issue(r)).rejects.toMatchObject(rejection(r));expect((await ref('partnerPaymentOperations',r.operationId).get()).updateTime?.isEqual(op.updateTime!)).toBe(true);await financialZero(r);});
 it('stale revision은 원 revision 보존·새 작업 수정은 정상 발행',async()=>{await seed();await put('appMeta',stateId,{companyId:'taebaek',partnerId,revision:1});const r=input('revision');await expect(issue(r)).rejects.toMatchObject(rejection(r));await financialZero(r,1);expect(await issue({...input('revision-new'),expectedRevision:1})).toMatchObject({status:'applied'});expect((await ref('appMeta',stateId).get()).get('revision')).toBe(2);});
 it('잘못된 은행은 거절 후 새 작업 계좌 수정 가능',async()=>{await seed();await put('cashAccounts',`${runId}-foreign`,{companyId:'punghoe',active:true});const r={...input('bank'),cashAccountId:`${runId}-foreign`};await expect(issue(r)).rejects.toMatchObject(rejection(r));await financialZero(r);await expect(issue({...r,cashAccountId:bankId})).rejects.toMatchObject({details:undefined});expect(await issue(input('bank-new'))).toMatchObject({status:'applied'});});
 it('같은 작업 병렬 거절은 감사1개·금융0',async()=>{await seed();await ref('appMeta','partnerPaymentCutover_taebaek').delete();const r=input('parallel-reject');const results=await Promise.allSettled([issue(r),issue(r)]);for(const result of results){expect(result.status).toBe('rejected');if(result.status==='rejected')expect(result.reason).toMatchObject(rejection(r));}expect((await db.collection('partnerPaymentOperations').get()).docs.filter(s=>s.id===r.operationId)).toHaveLength(1);await financialZero(r);});
 it('같은 작업 정상/거절 경쟁은 한 terminal 결과만 남긴다',async()=>{await seed();const r=input('race');const results=await Promise.allSettled([issue(r),issue({...r,expectedRevision:1})]);const op=await ref('partnerPaymentOperations',r.operationId).get();const cash=await ref('cashEntries',r.operationId).get();expect(op.exists).toBe(true);if(cash.exists){expect(op.get('status')).not.toBe('rejected');expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((await ref('appMeta',counterId).get()).get('last')).toBe(1);}else{expect(op.get('status')).toBe('rejected');await financialZero(r);}expect(results.filter(x=>x.status==='rejected'&&(x.reason as any).details===undefined)).toHaveLength(1);});
 it('실제 commit 직후 응답 유실은 같은 요청 duplicate·번호/정산1회',async()=>{await seed();const r=input('lost');const lossy={collection:db.collection.bind(db),runTransaction:async(run:any)=>{await db.runTransaction(run);throw new Error('response discarded after commit');}} as any;await expect(issue(r,lossy)).rejects.toThrow('response discarded');expect(await issue(r)).toMatchObject({status:'duplicate',docNo:'261003-001'});expect((await ref('appMeta',counterId).get()).get('last')).toBe(1);expect((await db.collection('settlements').where('operationId','==',r.operationId).get()).size).toBe(1);expect((await ref('appMeta',stateId).get()).get('revision')).toBe(1);});
 it('legacy 현재 release 거절 memo가 늦은 원 release 요청도 봉쇄한다',async()=>{await seed();await ref('appMeta','partnerPaymentCutover_taebaek').delete();const r=input('legacy-reject');await expect(issue(r)).rejects.toMatchObject(rejection(r));await put('appMeta','partnerPaymentCutover_taebaek',{companyId:'taebaek',enabled:true,legacyWritersBlocked:true,auditPassed:true});await expect(issue({...r,releaseId:'old-release'})).rejects.toMatchObject({details:undefined});await financialZero(r);});
 it('legacy 이미 applied 원 release는 새 release 불일치를 안전 거절로 바꾸지 않는다',async()=>{await seed();const r=input('legacy-applied');expect(await issue(r)).toMatchObject({status:'applied'});await put('appMeta','releaseCutover',{releaseId:'next-release',status:'active',voucherNotBefore:{taebaek:date}});await expect(issue({...r,releaseId:'next-release'})).rejects.toMatchObject({details:undefined});expect((await ref('cashEntries',r.operationId).get()).get('amount')).toBe(100);expect((await ref('appMeta',counterId).get()).get('last')).toBe(1);});
 it('과다 배분 도메인 거절은 금융0이고 새 수정 입력은 발행 가능',async()=>{await seed();const r={...input('overallocated'),amount:90};await expect(issue(r)).rejects.toMatchObject(rejection(r));await financialZero(r);expect((await ref('partnerPaymentOperations',r.operationId).get()).get('failureCode')).toBe('failed-precondition');expect(await issue(input('overallocated-new'))).toMatchObject({status:'applied'});});
});
