import { describe,it,expect } from 'vitest';
import { planUnitReturnReceipt,planUnitReturnIssue } from './returnUnitStockPlan';
import { buildProductLot,withCarryOverProductLot,deductLotsByQty,lotQtyRemaining } from '../../src/shared/lotUtils';
const input={operationId:'return-unit',companyId:'taebaek',date:'2026-10-07',createdAt:'2026-10-07T01:00:00Z',partnerId:'client',partnerName:'거래처',item:{id:'can',companyId:'taebaek',type:'wip',name:'참기름/16.5kg',unit:'캔',stock:5,lots:[]},quantityDelta:2,rawTargetExists:true};
describe('반품 개수 로트의 공용 순수 계산',()=>{
 it.each(['product','wip'])('%s 반품은 기존 이월·새 로트와 동치이며 원문을 유지한다',type=>{const original=structuredClone(input),plan=planUnitReturnReceipt({...input,item:{...input.item,type}},16.5);expect(plan.receipt.productLotId).toBe(`receipt:${plan.receiptId}`);expect(plan.nextStock).toBe(7);expect(lotQtyRemaining(plan.lots)).toBe(7);expect(plan.lots.map(row=>row.kgRemaining)).toEqual([82.5,33]);const carry=withCarryOverProductLot([],5,input.item.name,16.5,{id:`carry:${plan.receiptId}`,createdAt:input.createdAt,receivedDate:input.date});const received=buildProductLot({material:input.item.name,itemId:'can',supplierName:input.partnerName,supplierId:input.partnerId,qtyIn:2,unitKg:16.5,receivedDate:input.date});expect(plan.lots[0]).toEqual(carry[0]);expect(plan.lots[1]).toEqual({...received,id:`receipt:${plan.receiptId}`,createdAt:input.createdAt});expect(input).toEqual(original);expect(planUnitReturnReceipt(input,16.5)).toEqual(plan);});
 it('0 중량은 기존 입고처럼 허용하고 개수 근거는 남긴다',()=>{const plan=planUnitReturnReceipt(input,0);expect(plan.lots.map(row=>row.kgRemaining)).toEqual([0,0]);expect(plan.receipt.quantity).toBe(2);});
 it('기존 로트는 보존하고 매입 반품은 기존 FIFO와 동치다',()=>{const received=planUnitReturnReceipt(input,16.5);const state={...input,item:{...input.item,stock:7,lots:received.lots},quantityDelta:-6};const plan=planUnitReturnIssue(state,16.5),expected=deductLotsByQty(received.lots,6);expect(plan.nextStock).toBe(1);expect(plan.lots).toEqual(expected.lots);expect(plan.lotTaken).toEqual(expected.distribution);expect(plan.movement.lotTaken).toEqual(expected.distribution);expect(plan.lots.map(row=>row.kgRemaining)).toEqual([0,16.5]);expect(plan).not.toHaveProperty('receipt');});
 it('부족한 로트·다른 회사·벌크·비유한 중량은 원문을 바꾸지 않는다',()=>{const copy=structuredClone(input);expect(()=>planUnitReturnIssue({...input,quantityDelta:-6},16.5)).toThrow('부족');for(const item of [{...input.item,companyId:'punghoe'},{...input.item,subtype:'벌크'},{...input.item,type:'raw'},{...input.item,lots:[{qtyRemaining:1}]}])expect(()=>planUnitReturnReceipt({...input,item} as typeof input,16.5)).toThrow();expect(()=>planUnitReturnReceipt(input,NaN)).toThrow();expect(input).toEqual(copy);});
 it('일반 입고와 동일하게 소수 셋째 자리 수량·재고만 허용한다',()=>{expect(planUnitReturnReceipt({...input,quantityDelta:1.005},0).nextStock).toBe(6.005);expect(()=>planUnitReturnReceipt({...input,quantityDelta:0.0004},0)).toThrow();});
});
