import { beforeEach, expect, it, vi } from 'vitest';
import { deleteIssuedStatement } from './deleteIssuedStatementService';
const state=vi.hoisted(()=>({docs:new Map<string,any>(),writes:[] as any[],claim:'taebaek',beforeTx:undefined as (()=>void)|undefined}));
vi.mock('../firebase',()=>({db:{},authReady:Promise.resolve(),auth:{currentUser:{getIdTokenResult:async()=>({claims:{companyId:state.claim}})}}}));
vi.mock('firebase/firestore',()=>{
 const snapshot=(ref:any)=>{const exists=state.docs.has(ref.path),data=exists?structuredClone(state.docs.get(ref.path)):undefined;return {id:ref.id,exists:()=>exists,data:()=>data};};
 return {doc:(_:unknown,col:string,id:string)=>({id,path:`${col}/${id}`}),collection:(_:unknown,col:string)=>col,where:(field:string,_:unknown,value:unknown)=>({field,value}),query:(col:string,...filters:any[])=>({col,filters}),deleteField:()=> 'DELETE',getDoc:async(ref:any)=>snapshot(ref),
 getDocs:async({col,filters}:any)=>({docs:[...state.docs].filter(([path,row])=>path.startsWith(`${col}/`)&&filters.every((f:any)=>row[f.field]===f.value)).map(([path])=>snapshot({path,id:path.split('/')[1]}))}),
 runTransaction:async(_:unknown,callback:any)=>{state.beforeTx?.();const pending:any[]=[];await callback({get:async(ref:any)=>snapshot(ref),update:(ref:any,patch:any)=>pending.push(['update',ref.path,patch]),delete:(ref:any)=>pending.push(['delete',ref.path]),set:(ref:any,data:any)=>pending.push(['set',ref.path,data])});state.writes=pending;for(const[op,path,patch]of pending){if(op==='delete')state.docs.delete(path);else{const row=op==='set'?{}:{...state.docs.get(path)};for(const[key,value]of Object.entries(patch)){if(value==='DELETE')delete row[key];else row[key]=value;}state.docs.set(path,row);}}},};
});
beforeEach(()=>{state.docs.clear();state.writes=[];state.claim='taebaek';state.beforeTx=undefined;state.docs.set('issuedStatements/s1',{companyId:'taebaek',partnerId:'p1',orderId:'o1',purchaseOrderIds:['po1'],docNo:'261001-001'});state.docs.set('orders/o1',{companyId:'taebaek',linkedStatementId:'s1',linkedStatementAt:'old',status:'delivered',stock:99});state.docs.set('purchaseOrders/po1',{companyId:'taebaek',linkedStatementId:'s1',linkedStatementAt:'old',status:'invoiced'});state.docs.set('settlements/a1',{companyId:'taebaek',statementId:'s1',cashEntryId:'cash',amount:100});});
it('전표·매칭과같은ID연결을원자삭제하고상태재고번호는보존한다',async()=>{await deleteIssuedStatement('taebaek','s1');expect(state.docs.has('issuedStatements/s1')).toBe(false);expect(state.docs.has('settlements/a1')).toBe(false);expect(state.docs.get('orders/o1')).toEqual({companyId:'taebaek',status:'delivered',stock:99});expect(state.docs.get('purchaseOrders/po1')).toEqual({companyId:'taebaek',status:'invoiced'});});
it('조회후다른전표로연결된문서는그대로둔다',async()=>{state.beforeTx=()=>{state.docs.get('orders/o1').linkedStatementId='other';state.docs.get('settlements/a1').statementId='other';};await deleteIssuedStatement('taebaek','s1');expect(state.docs.get('orders/o1').linkedStatementId).toBe('other');expect(state.docs.get('settlements/a1').statementId).toBe('other');});
it('원본문서참조는회사없는태백문서와옛PO연결필드도보완한다',async()=>{state.docs.set('issuedStatements/s1',{orderId:'o1',confirmedProductIds:['po1']});state.docs.get('orders/o1').companyId=undefined;state.docs.get('purchaseOrders/po1').companyId=undefined;await deleteIssuedStatement('taebaek','s1');expect(state.docs.get('orders/o1').linkedStatementId).toBeUndefined();expect(state.docs.get('purchaseOrders/po1').linkedStatementId).toBeUndefined();});
it('로그인회사와요청회사가다르면조회전에거절한다',async()=>{await expect(deleteIssuedStatement('punghoe','s1')).rejects.toThrow('권한');expect(state.writes).toEqual([]);});
it('전표회사불일치와없는전표는삭제하지않는다',async()=>{state.docs.get('issuedStatements/s1').companyId='punghoe';await expect(deleteIssuedStatement('taebaek','s1')).rejects.toThrow('다른 회사');state.docs.delete('issuedStatements/s1');await expect(deleteIssuedStatement('taebaek','s1')).rejects.toThrow('찾을 수');expect(state.writes).toEqual([]);});
it('최신전표의원본연결이바뀌면전체삭제를거절한다',async()=>{state.beforeTx=()=>{state.docs.get('issuedStatements/s1').orderId='new-order';};await expect(deleteIssuedStatement('taebaek','s1')).rejects.toThrow('연결이 변경');expect(state.writes).toEqual([]);expect(state.docs.has('settlements/a1')).toBe(true);});
it('트랜잭션에서연결문서회사변경을발견하면어떤삭제도하지않는다',async()=>{state.beforeTx=()=>{state.docs.get('orders/o1').companyId='punghoe';};await expect(deleteIssuedStatement('taebaek','s1')).rejects.toThrow('다른 회사');expect(state.writes).toEqual([]);expect(state.docs.has('issuedStatements/s1')).toBe(true);});
it('원본에없는회사범위역방향연결도해제하되타회사는유지한다',async()=>{state.docs.set('orders/reverse',{companyId:'taebaek',linkedStatementId:'s1'});state.docs.set('orders/foreign',{companyId:'punghoe',linkedStatementId:'s1'});await deleteIssuedStatement('taebaek','s1');expect(state.docs.get('orders/reverse').linkedStatementId).toBeUndefined();expect(state.docs.get('orders/foreign').linkedStatementId).toBe('s1');});
it('기존 거래처 정산 revision을 올리고 다른 메타 필드는 유지한다',async()=>{state.docs.set('appMeta/partnerPaymentState_taebaek_p1',{companyId:'taebaek',partnerId:'p1',revision:5,extra:'preserve'});await deleteIssuedStatement('taebaek','s1');expect(state.docs.get('appMeta/partnerPaymentState_taebaek_p1')).toEqual({companyId:'taebaek',partnerId:'p1',revision:6,extra:'preserve'});});
it('손상된 정산 revision이면 전표와 연결을 삭제하지 않는다',async()=>{state.docs.set('appMeta/partnerPaymentState_taebaek_p1',{companyId:'taebaek',partnerId:'p1',revision:-1});await expect(deleteIssuedStatement('taebaek','s1')).rejects.toThrow('손상');expect(state.writes).toEqual([]);});
