import {doc,getDoc} from 'firebase/firestore';
import {httpsCallable} from 'firebase/functions';
import {auth,authReady,db,functions} from '../firebase';
import type {CompanyId,CashAccount} from '../types';
import {requireActiveReleaseId} from '../releaseGate';
export type TransferPartner={id:string;companyId:CompanyId;name:string;revision:number;available:number};
export type TransferOptions={from:{companyId:CompanyId;accounts:CashAccount[];partners:TransferPartner[]};to:{companyId:CompanyId;accounts:CashAccount[];partners:TransferPartner[]};releaseId:string};
export type TransferDraft={from:CompanyId;to:CompanyId;tradeDate:string;amount:number;overKind:'선급금'|'대여금';fromAccountId:string;toAccountId:string;fromPartnerId:string;toPartnerId:string;expectedFromRevision:number;expectedToRevision:number;note?:string};
type Command=TransferDraft&{operationId:string;releaseId:string};
const running=new Set<string>();
const canonical=(value:any):any=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([,item])=>item!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,canonical(item)])):value;
const hash=async(value:unknown)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(canonical(value))))),byte=>byte.toString(16).padStart(2,'0')).join('');
async function context(companyId:CompanyId){await authReady;const user=auth.currentUser;const assert=async()=>{const token=await user?.getIdTokenResult();if(!user||auth.currentUser?.uid!==user.uid||token?.claims.companyId!==companyId||token.claims.isAdmin!==true)throw new Error('관리자 회사 권한이 바뀌었습니다.');};await assert();return {user:user!,assert};}
export async function prepareTransferOptions(from:CompanyId,to:CompanyId,tradeDate:string):Promise<TransferOptions>{const {assert}=await context(from);const gate=await getDoc(doc(db,'appMeta','releaseCutover'));await assert();const releaseId=requireActiveReleaseId(gate.data());const {data}=await httpsCallable(functions,'prepareInterCompanyTransferCommand')({from,to,tradeDate,releaseId});await assert();const options=data as TransferOptions;if(options?.from?.companyId!==from||options?.to?.companyId!==to||options.releaseId!==releaseId)throw new Error('회사이체 선택지를 확인할 수 없습니다.');for(const side of [options.from,options.to]){if(!Array.isArray(side.accounts)||!Array.isArray(side.partners)||side.accounts.some(account=>!account.id||account.companyId!==side.companyId||account.type!=='통장'||account.active!==true)||side.partners.some(partner=>!partner.id||partner.companyId!==side.companyId||!Number.isSafeInteger(partner.revision)||partner.revision<0||!Number.isSafeInteger(partner.available)||partner.available<0))throw new Error('각 회사의 실제 계좌·거래처를 확인해 주세요.');}return options;}
const keyOf=(companyId:CompanyId,uid:string)=>`company-transfer-pending:${companyId}:${uid}`;
const calendarDay=(value:unknown)=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value+'T00:00:00Z'))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
function valid(command:any,companyId:CompanyId):command is Command{return !!command&&command.from===companyId&&command.to!==companyId&&['taebaek','punghoe'].includes(command.to)&&['선급금','대여금'].includes(command.overKind)&&Number.isSafeInteger(command.amount)&&command.amount>0&&[command.expectedFromRevision,command.expectedToRevision].every(value=>Number.isSafeInteger(value)&&value>=0)&&typeof command.operationId==='string'&&/^[A-Za-z0-9_-]{1,150}$/.test(command.operationId)&&typeof command.releaseId==='string'&&/^[A-Za-z0-9_-]{1,100}$/.test(command.releaseId)&&['fromAccountId','toAccountId','fromPartnerId','toPartnerId'].every(key=>typeof command[key]==='string'&&!!command[key]&&!command[key].includes('/'))&&calendarDay(command.tradeDate)&&command.fromPartnerId!==command.toPartnerId&&(command.note===undefined||typeof command.note==='string'&&command.note.length<=500);}
export function hasPendingTransfer(companyId:CompanyId):boolean{try{return !!auth.currentUser?.uid&&localStorage.getItem(keyOf(companyId,auth.currentUser.uid))!==null;}catch{return false;}}
async function send(companyId:CompanyId,draft?:TransferDraft,releaseId?:string){const {user,assert}=await context(companyId),key=keyOf(companyId,user.uid);if(running.has(key))throw new Error('회사이체를 저장 중입니다.');running.add(key);try{let saved=localStorage.getItem(key);let command:Command;if(saved!==null){try{command=JSON.parse(saved);}catch{throw new Error('보관된 회사이체 요청을 확인해야 합니다.');}if(!valid(command,companyId))throw new Error('보관된 회사이체 요청이 손상되었습니다.');if(draft){const business=(row:TransferDraft)=>{const {expectedFromRevision:_a,expectedToRevision:_b,...rest}=row;return rest;};const {operationId:_id,releaseId:_release,...stored}=command;if(JSON.stringify(canonical(business(stored)))!==JSON.stringify(canonical(business({...draft,note:draft.note?.trim()??''}))))throw new Error('이전 결과가 불확실합니다. 이전 저장 재시도로 확인해 주세요.');}}
 else{if(!draft||!releaseId)throw new Error('이전 회사이체 요청이 없습니다.');command={...draft,note:draft.note?.trim()??'',operationId:`transfer-${crypto.randomUUID()}`,releaseId};if(!valid(command,companyId))throw new Error('회사이체 입력을 확인해 주세요.');await assert();saved=JSON.stringify(command);localStorage.setItem(key,saved);}
 const requestHash=await hash({...command,note:command.note?.trim()??''});await assert();let callError:unknown;try{await httpsCallable(functions,'recordInterCompanyTransferCommand')(command);}catch(error){callError=error;}const receipt=await getDoc(doc(db,'companyTransferOperations',command.operationId));await assert();if(!receipt.exists()){if(callError)throw callError;throw new Error('이체 결과가 불확실합니다. 같은 요청으로 재시도해 주세요.');}const row=receipt.data();if(row.companyId!==companyId||row.authUid!==user.uid||row.from!==command.from||row.to!==command.to||row.requestHash!==requestHash||!row.command||await hash(row.command)!==await hash(command))throw new Error('회사이체 감사가 원 요청과 일치하지 않습니다.');if(row.status==='rejected'){if(!['invalid-argument','failed-precondition'].includes(row.failureCode)||typeof row.failureMessage!=='string')throw new Error('이체 거절 감사를 확인할 수 없습니다.');await assert();if(localStorage.getItem(key)===saved)localStorage.removeItem(key);throw Object.assign(new Error(row.failureMessage),{knownRejected:true});}if(row.status!=='applied'||row.outCashEntryId!==`${command.operationId}-out`||row.inCashEntryId!==`${command.operationId}-in`||typeof row.outDocNo!=='string'||!row.outDocNo||typeof row.inDocNo!=='string'||!row.inDocNo)throw new Error('회사이체 완료 감사를 확인할 수 없습니다.');await assert();if(localStorage.getItem(key)===saved)localStorage.removeItem(key);return {outDocNo:row.outDocNo,inDocNo:row.inDocNo};}finally{running.delete(key);}}
export const saveInterCompanyTransfer=(draft:TransferDraft,releaseId:string)=>send(draft.from,draft,releaseId);
export const resumeInterCompanyTransfer=(companyId:CompanyId)=>send(companyId);
