import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs } from 'firebase/firestore';
import { getAuth, signInAnonymously } from 'firebase/auth';
const app = initializeApp({ apiKey: 'AIzaSyBOppTpeiRV1lQDU9ijQGVHQRS-zQW-OOE', authDomain: 'taebaek-3abe4.firebaseapp.com', projectId: 'taebaek-3abe4' });
const db = getFirestore(app);
await signInAnonymously(getAuth(app));
const items = (await getDocs(collection(db, 'items'))).docs.map(d => ({ id: d.id, ...d.data() }));
const f = (await getDocs(collection(db, 'item_formula'))).docs.map(d => ({ id: d.id, ...d.data() }));
const prod = items.filter(i => !i.archived && i.category === 'product');
const keys = {};
for (const p of prod) keys[p.품목 || '(품목키없음)'] = (keys[p.품목 || '(품목키없음)'] ?? 0) + 1;
console.log(`완제품 ${prod.length}개가 쓰는 품목키 ${Object.keys(keys).length}종:`);
for (const [k, n] of Object.entries(keys).sort((a,b)=>b[1]-a[1])) console.log(`   ${String(n).padStart(3)}개  ${k}`);
console.log(`\nitem_formula(DB) ${f.length}건`);
