import { mkdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { adminDb } from './_admin.mts';
const db=adminDb(), partnerId='c-1779251336139';
const first='partner-payment-a3a5fcc1-f0f9-45c4-8d88-58bd53512df9', extra='partner-payment-f7b799e3-97aa-4d9f-ab1c-19d25c043416';
const paths=[`cashEntries/${first}`,`cashEntries/${extra}`,`partnerPaymentOperations/${first}`,`partnerPaymentOperations/${extra}`,`appMeta/partnerPaymentState_taebaek_${partnerId}`];
const refs=paths.map(p=>db.doc(p));
const before=await Promise.all(refs.map(r=>r.get()));
const linked=await Promise.all([first,extra].map(id=>db.collection('settlements').where('cashEntryId','==',id).get()));
const settlements=linked.flatMap(s=>s.docs);
if(before[0].get('amount')!==7603640 || before[1].get('amount')!==693000 || before.slice(0,2).some(s=>s.get('partnerId')!==partnerId || s.get('companyId')!=='taebaek')) throw new Error('대상 지불 불일치');
const applications=[{statementId:'stmt-1790914462792',amount:5403640,accountCode:'251'},{statementId:'stmt-1791261885119',amount:2200000,accountCode:'251'}];
const newCash={...before[0].data()!,lines:[{accountCode:'251',amount:7603640}]};
const canonical=(v:any):any=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[k,canonical(x)])):v;
const business={companyId:newCash.companyId,partnerId:newCash.partnerId,date:newCash.date,cashAccountId:newCash.cashAccountId,dir:newCash.dir,amount:newCash.amount,lines:newCash.lines,note:newCash.note};
const entryHash=createHash('sha256').update(JSON.stringify(canonical(business))).digest('hex');
const correctedSettlements=applications.map(a=>({statementId:a.statementId,amount:a.amount}));
console.log(JSON.stringify({first:before[0].get('docNo'),cancel:before[1].get('docNo'),linked:settlements.length,actualPaid:7603640,applications}));
if(!process.argv.includes('--apply')) process.exit(0);
mkdirSync('outputs',{recursive:true});
writeFileSync('outputs/cheongjeong-payment-backup-20261006.json',JSON.stringify([...before,...settlements].map(s=>({path:s.ref.path,data:s.data()})),null,2));
await db.runTransaction(async tx=>{
  const current=await Promise.all([...before,...settlements].map(s=>tx.get(s.ref)));
  current.forEach((s,i)=>{if(!s.updateTime?.isEqual([...before,...settlements][i].updateTime!)) throw new Error('정정 중 자료 변경');});
  tx.update(refs[0],{lines:newCash.lines});
  tx.delete(refs[1]);
  tx.update(refs[2],{entryHash,applications,settlements:correctedSettlements,correctionReason:'사용자 확인 실제 송금 7603640원, 과거 반품 배분 오류 정정',correctedAt:new Date().toISOString()});
  tx.update(refs[3],{status:'cancelled',cancelledAt:new Date().toISOString(),cancelReason:'실제 송금 없음: 반품 배분 오류로 추가 등록'});
  tx.update(refs[4],{revision:before[4].get('revision')+1});
  settlements.forEach(s=>tx.delete(s.ref));
  correctedSettlements.forEach(a=>tx.set(db.doc(`settlements/st-${first}-${a.statementId}`),{companyId:'taebaek',operationId:first,cashEntryId:first,statementId:a.statementId,amount:a.amount,createdAt:newCash.createdAt}));
});
const [saved,cancelled]=await Promise.all([refs[0].get(),refs[1].get()]);
if(saved.get('lines')[0].amount!==7603640 || cancelled.exists) throw new Error('사후 확인 실패');
console.log('정정 재조회 완료: 실제 지불 7603640원, 추가 지불 없음');
